### ISSUE TITLE
Question: Why aren't there any release tarballs here?

### ISSUE THREAD

**Issue by carlorosati** [dtrace4linux/linux#126]
Are the release tarballs over at [ftp://crisp.publicvm.com/pub/release/website/dtrace](ftp://crisp.publicvm.com/pub/release/website/dtrace) legit?

**Comment by carlorosati** [comment]
It's mentioned in the README

**Comment by dtrace4linux** [comment]
as per README, should be in ftp://crispeditor.co.uk.

thanks
